param(
  [Parameter(Mandatory=$true)][string]$ProjectName,
  [Parameter(Mandatory=$true)][string]$Objective,
  [Parameter(Mandatory=$true)][string]$RepoUrl,
  [Parameter(Mandatory=$true)][string]$LocalRepoPath,
  [Parameter(Mandatory=$false)][string]$Owner = "askairo",
  [Parameter(Mandatory=$false)][string]$DocsRoot = "D:\znder\Obsidian\business\03-req"
)

$today = Get-Date -Format "yyyy-MM-dd"
$projectDir = Join-Path $DocsRoot $ProjectName
New-Item -ItemType Directory -Force -Path $projectDir | Out-Null

\$overviewPath = Join-Path $projectDir "00-overview.md"
$roadmapPath = Join-Path $projectDir "10-roadmap.md"

$overview = @"
# 00-overview

- project: `$ProjectName`
- status: `kickoff`
- createdAt: `$today`
- owner: `$Owner`

## Objective

$Objective

## Scope

- In scope: desktop environment switch (Windows first)
- In scope: variables orchestration (and optional hosts integration)
- Out of scope: full cloud control plane in MVP

## Repositories and Paths

- GitHub: `$RepoUrl`
- Local Repo: `$LocalRepoPath`
- Project Docs: `$projectDir`

## Architecture Direction

- Platform: Windows first, then macOS/Linux
- Runtime/Stack: Tauri + React + Rust
- Key constraints: lightweight, secure handling of secrets, reproducible switching

## Milestones

1. MVP desktop switching loop available
2. Security and observability hardening
3. Cross-platform expansion
"@

$roadmap = @"
# 10-roadmap

## Execution Checklist

- [ ] P1 Apply model upgrade: session/persistent modes
- [ ] P2 Result observability: before/after + status detail
- [ ] P3 Hook support: post-switch commands
- [ ] P4 UX hardening: error handling + current env indicator
- [ ] P5 Verification: build + functional switching checks

## Verification Plan

- [ ] `npm run build`
- [ ] `cargo check` (tauri backend)
- [ ] Manual apply flow for `dev` / `sit`

## Change Log

- `$today`: kickoff docs generated by `project-kickoff-flow` script.

## Risks and Decisions

- Risk: environment drift across shells/processes
- Decision: keep docs outside repo under `03-req/<project>/`

## Next Actions

1. Fill concrete milestone acceptance criteria
2. Execute P1 and record verification evidence
"@

Set-Content -Path $overviewPath -Value $overview -Encoding UTF8
Set-Content -Path $roadmapPath -Value $roadmap -Encoding UTF8

Write-Host "Generated: $overviewPath"
Write-Host "Generated: $roadmapPath"
