param(
  [Parameter(Mandatory=$true)][string]$ProjectName,
  [Parameter(Mandatory=$true)][string]$Objective,
  [Parameter(Mandatory=$true)][string]$RepoUrl,
  [Parameter(Mandatory=$true)][string]$LocalRepoPath,
  [Parameter(Mandatory=$false)][string]$Owner = "askairo",
  [Parameter(Mandatory=$false)][string]$DocsRoot = "",
  [Parameter(Mandatory=$false)][string]$ConfigPath = "",
  [Parameter(Mandatory=$false)][switch]$SaveConfig
)

function Get-DefaultConfigPath {
  if ($env:CODEX_HOME) {
    return (Join-Path $env:CODEX_HOME "local-config\p-bootstrap\paths.yaml")
  }
  if ($HOME) {
    return (Join-Path $HOME ".codex\local-config\p-bootstrap\paths.yaml")
  }

  throw "Unable to resolve a local config path. Provide -ConfigPath explicitly."
}

function Resolve-ExistingConfigPath {
  param([string]$ExplicitPath)

  if ($ExplicitPath -and (Test-Path -LiteralPath $ExplicitPath)) {
    return $ExplicitPath
  }

  $candidates = @()
  if ($env:CODEX_HOME) {
    $candidates += (Join-Path $env:CODEX_HOME "local-config\p-bootstrap\paths.yaml")
  }
  if ($HOME) {
    $candidates += (Join-Path $HOME ".codex\local-config\p-bootstrap\paths.yaml")
  }

  foreach ($candidate in $candidates) {
    if ($candidate -and (Test-Path -LiteralPath $candidate)) {
      return $candidate
    }
  }

  return ""
}

function Get-ConfigValue {
  param(
    [Parameter(Mandatory=$true)][string]$Path,
    [Parameter(Mandatory=$true)][string]$Key
  )

  if (-not (Test-Path -LiteralPath $Path)) {
    return ""
  }

  $pattern = "^\s*$([regex]::Escape($Key))\s*:\s*(.+?)\s*$"
  foreach ($line in Get-Content -LiteralPath $Path) {
    if ($line -match $pattern) {
      return $Matches[1].Trim().Trim('"').Trim("'")
    }
  }

  return ""
}

function Write-PathConfig {
  param(
    [Parameter(Mandatory=$true)][string]$Path,
    [Parameter(Mandatory=$true)][string]$DocsRoot
  )

  $configDir = Split-Path -Parent $Path
  New-Item -ItemType Directory -Force -Path $configDir | Out-Null

  $content = @"
version: 1

docs:
  root: $DocsRoot
"@

  Set-Content -Path $Path -Value $content -Encoding UTF8
}

function Resolve-DocsDirectory {
  param(
    [string]$ProjectName,
    [string]$DocsRoot,
    [string]$ConfigPath
  )

  $resolvedConfigPath = Resolve-ExistingConfigPath -ExplicitPath $ConfigPath
  $configuredDocsRoot = ""

  if ($resolvedConfigPath) {
    $configuredDocsRoot = Get-ConfigValue -Path $resolvedConfigPath -Key "root"
  }

  $effectiveDocsRoot = if ($DocsRoot) { $DocsRoot } elseif ($configuredDocsRoot) { $configuredDocsRoot } else { "" }

  if (-not $effectiveDocsRoot) {
    throw "Docs root is not configured. Provide -DocsRoot, then rerun with -SaveConfig to persist it."
  }

  return (Join-Path $effectiveDocsRoot $ProjectName)
}

if ($SaveConfig) {
  $targetConfigPath = if ($ConfigPath) { $ConfigPath } else { Get-DefaultConfigPath }

  if (-not $DocsRoot) {
    throw "Cannot save config without -DocsRoot."
  }

  Write-PathConfig -Path $targetConfigPath -DocsRoot $DocsRoot
  Write-Host "Saved config: $targetConfigPath"
}

$today = Get-Date -Format "yyyy-MM-dd"
$projectDir = Resolve-DocsDirectory `
  -ProjectName $ProjectName `
  -DocsRoot $DocsRoot `
  -ConfigPath $ConfigPath
New-Item -ItemType Directory -Force -Path $projectDir | Out-Null

$overviewPath = Join-Path $projectDir "00-overview.md"
$roadmapPath = Join-Path $projectDir "10-roadmap.md"

$overview = @"
# 00-overview

- project: `$ProjectName`
- status: `kickoff`
- createdAt: `$today`
- owner: `$Owner`

## Objective

$Objective

## Scope

- In scope: desktop environment switch (Windows first)
- In scope: variables orchestration (and optional hosts integration)
- Out of scope: full cloud control plane in MVP

## Repositories and Paths

- GitHub: `$RepoUrl`
- Local Repo: `$LocalRepoPath`
- Project Docs: `$projectDir`

## Architecture Direction

- Platform: Windows first, then macOS/Linux
- Runtime/Stack: Tauri + React + Rust
- Key constraints: lightweight, secure handling of secrets, reproducible switching

## Milestones

1. MVP desktop switching loop available
2. Security and observability hardening
3. Cross-platform expansion
"@

$roadmap = @"
# 10-roadmap

## Execution Checklist

- [ ] P1 Apply model upgrade: session/persistent modes
- [ ] P2 Result observability: before/after + status detail
- [ ] P3 Hook support: post-switch commands
- [ ] P4 UX hardening: error handling + current env indicator
- [ ] P5 Verification: build + functional switching checks

## Verification Plan

- [ ] `npm run build`
- [ ] `cargo check` (tauri backend)
- [ ] Manual apply flow for `dev` / `sit`

## Change Log

- `$today`: kickoff docs generated by `p-bootstrap` script.

## Risks and Decisions

- Risk: environment drift across shells/processes
- Decision: keep project-management docs outside the code repo.

## Next Actions

1. Fill concrete milestone acceptance criteria
2. Execute P1 and record verification evidence
"@

Set-Content -Path $overviewPath -Value $overview -Encoding UTF8
Set-Content -Path $roadmapPath -Value $roadmap -Encoding UTF8

Write-Host "Generated: $overviewPath"
Write-Host "Generated: $roadmapPath"
