const fs = require('fs');
const path = require('path');
const XLSX = require('xlsx');

function parseArgs(argv) {
  const args = {};
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith('--')) {
      const key = a.slice(2);
      const next = argv[i + 1];
      if (!next || next.startsWith('--')) {
        args[key] = true;
      } else {
        args[key] = next;
        i++;
      }
    }
  }
  return args;
}

function camelToSnake(s) {
  return s.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
}

function cleanHeader(h) {
  return String(h || '').replace(/^[*\s　]+/, '').trim();
}

function esc(v) {
  return String(v).replace(/'/g, "''");
}

function readEntity(entityPath) {
  const text = fs.readFileSync(entityPath, 'utf8');
  const tableMatch = text.match(/@TableName\s*\(\s*value\s*=\s*"([^"]+)"\s*\)/);
  if (!tableMatch) throw new Error('未找到 @TableName(value="...")');
  const tableName = tableMatch[1];

  const lines = text.split(/\r?\n/);
  const fields = [];
  let skipNextField = false;

  for (const line of lines) {
    if (/@TableField\s*\(\s*exist\s*=\s*false\s*\)/.test(line)) {
      skipNextField = true;
      continue;
    }
    const m = line.match(/^\s*private\s+([\w<>?, ]+)\s+(\w+)\s*;/);
    if (!m) continue;
    const name = m[2];
    if (/serialVersionUID/.test(name)) continue;
    if (skipNextField) {
      skipNextField = false;
      continue;
    }
    fields.push({
      fieldName: name,
      columnName: camelToSnake(name),
    });
  }

  return { tableName, fields };
}

function main() {
  const args = parseArgs(process.argv);
  if (!args.excel || !args.entity || !args.out) {
    throw new Error('参数缺失: --excel --entity --out 必填');
  }

  const wb = XLSX.readFile(args.excel);
  const sheetName = args.sheet || wb.SheetNames[0];
  const ws = wb.Sheets[sheetName];
  if (!ws) throw new Error(`未找到 sheet: ${sheetName}`);

  const rows = XLSX.utils.sheet_to_json(ws, { defval: '', raw: false });
  if (!rows.length) throw new Error('Excel 无数据行');

  const { tableName, fields } = readEntity(args.entity);

  const headerMap = {};
  const firstRow = rows[0];
  for (const key of Object.keys(firstRow)) {
    headerMap[cleanHeader(key)] = key;
  }

  const resolved = [];
  for (const f of fields) {
    let key = null;
    if (headerMap[f.fieldName]) key = headerMap[f.fieldName];
    else if (headerMap[f.columnName]) key = headerMap[f.columnName];
    resolved.push({ ...f, excelKey: key });
  }

  if (args.strict) {
    const missing = resolved.filter((x) => !x.excelKey).map((x) => x.fieldName);
    if (missing.length) throw new Error('严格模式下存在未映射字段: ' + missing.join(', '));
  }

  const auditCols = ['create_id', 'create_name', 'create_by', 'update_id', 'update_name', 'update_by'];
  const auditVals = ['1', "'超级管理员'", "'admin'", '1', "'超级管理员'", "'admin'"];

  const cols = resolved.filter((x) => x.excelKey).map((x) => x.columnName);
  const allCols = [...cols, ...auditCols];

  const valuesSql = rows
    .map((row) => {
      const vals = resolved
        .filter((x) => x.excelKey)
        .map((x) => {
          const v = row[x.excelKey];
          if (v === '' || v === null || v === undefined) return 'NULL';
          return `'${esc(v)}'`;
        });
      return `(${[...vals, ...auditVals].join(', ')})`;
    })
    .join(',\n');

  const out = `-- generated by excel2sql\nINSERT INTO ${tableName} (${allCols.join(', ')}) VALUES\n${valuesSql};\n`;
  fs.writeFileSync(args.out, out, 'utf8');
  console.log(path.resolve(args.out));
}

main();
